### ISSUE TITLE
en-GB language option no longer works for v0.4.0

### ISSUE THREAD

**Issue by songololo** [timlrx/rehype-citation#12]
The `en-GB` language option no longer seems to work since upgrading to v0.4.0

**Comment by timlrx** [comment]
@songololo, the `en-GB` xml was not present even in previous versions, it just did not throw an error. With v0.4.0, rehype-citation now throws an error if the locale does not exist. 

By default, only `en-US` is built-in. To use `en-GB` you could either [create your own version of the plugin]( https://github.com/timlrx/rehype-citation#generating-your-own-remark-citation-plugins) or set `options.lang` to the local or URL path of the locale file - that's a new feature in v0.4.0. I.e.

```
lang: https://raw.githubusercontent.com/citation-style-language/locales/master/locales-en-GB.xml
```

Hope that helps!

**Comment by songololo** [comment]
awesome, thanks!
