### ISSUE TITLE
Bug in HTML generation when using 10 or more references with numeric style and linked citations

### ISSUE THREAD

**Issue by marc-b2** [timlrx/rehype-citation#21]
## Issue
When using 10 or more distinct references in one file with a numeric style csl **and** `linkCitations` enabled the HTML generation breaks.

## Steps to reproduce
Using the linkCitaion example from the demo app:
* use numeric citation style
* add up to 10 literature entries to bib file
* add up to diferent 10 references in markdown example text

Or simply checkout my [fork](https://github.com/marc-b2/rehype-citation-test).

**Comment by timlrx** [comment]
Thanks, able to reproduce the bug. Let me see what's the issue.

**Comment by timlrx** [comment]
@marc-b2 fixed and published as v1.0.1

**Comment by marc-b2** [comment]
nice! thanks for the quick response!
