### ISSUE TITLE
Cannot find references if they're inside a table

### ISSUE THREAD

**Issue by 0xCaso** [timlrx/rehype-citation#24]
Hi there, I'm using the plugin with docusaurus.

I have a table, and if I put the citation (`[@example]`) inside a table, the plugin won't be able to find it.

Example:

| Key Scheme | Description |
|------------|-------------|
| sr25519    | Schnorr signature on Ristretto compressed ed25519 points as implemented in TODO|
| ed25519    | The ed25519 signature complies with [@josefsson_edwards-curve_2017] except for the verification process which adhere to Ed25519 Zebra variant specified in [@devalence_ed25519zebra_2020]. In short, the signature point is not assumed to be on in the prime ordered subgroup group. As such, the verifier must explicitly clear the cofactor during the course of verifying the signature equation. |
| secp256k1  | Only for outgoing transfer transactions. |

**Comment by timlrx** [comment]
Hi @0xCaso, sorry for the delay. Have fixed the issue in v1.0.2.
