### ISSUE TITLE
Cannot redefine property: Cite

### ISSUE THREAD

**Issue by adnjoo** [timlrx/rehype-citation#36]
Hi I tried using rehype-citation (to help format some markdown files) in a Next.js 13.5.4 application like this:

rehype-citation version 0.2.0

```
import rehypeCitation from 'rehype-citation';
...
options.rehypePlugins = [
        ...(options.rehypePlugins ?? []),
        rehypeSlug,
        rehypeAutolinkHeadings,
        rehypeKatex,
        [rehypeCitation, { path: path.join(root, 'data') }],
        [rehypePrismPlus, { ignoreMissing: true }],
        rehypePresetMinify,
      ];
return options;
```
and get this error: Cannot redefine property: Cite

![Screenshot 2023-12-05 at 7 12 12 PM](https://github.com/timlrx/rehype-citation/assets/22807629/cdc78f48-9ed9-4d5b-aa11-c740116194ee)

**Comment by timlrx** [comment]
It should work and a demo example is available in the repo or at my [blog template](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/contentlayer.config.ts#L147). Which framework are you using to process the markdown content? If you are using mdx-bundler or contentlayer, you will need to use v1 of the plugin as the underlying dependencies have not yet been updated to the latest unified js versions.
