### ISSUE TITLE
noCite replaces citations

### ISSUE THREAD

**Issue by igor-koop** [timlrx/rehype-citation#42]
I am using rehype-citation (v2.1.2) on my Astro generate site. If noCite option is used (in astro.config.mjs or frontmatter), the current bibliography is replaced by items specified in noCite, while citations on the page are not included. I don't know what caused the issue and if it's related to Astro.

**Comment by halafy-ds** [comment]
@igor-koop can you check with this merge if you still have the noCite issue?

**Comment by igor-koop** [comment]
Hello, I am sadly still experiencing the noCite issues, even with fixed utils.js

**Comment by halafy-ds** [comment]
@igor-koop  hope this one helps.
