### ISSUE TITLE
Astro frontmatter support

### ISSUE THREAD

**Issue by igor-koop** [timlrx/rehype-citation#43]
The ability to define noCite and CSL in frontmatter is handy. Currently, it is not directly possible to utilise this feature in Astro, as the way to access the frontmatter is via `file.data.astro.frontmatter` and not `file.data.frontmatter` property. One could overcome this with wrappers, but appending the property into the plugin or maybe even including a dedicated option to add custom properties for noCite and CSL would be beneficial.

**Comment by timlrx** [comment]
Thanks, I can see that the plugin would not work as intended as the wrong field is being parsed for astro. Will fix it next day or 2.

**Comment by timlrx** [comment]
Added support to parse astro frontmatter and with @halafy-ds fix for noCite, it should work as intended now. Try out v2.2.0!
