### ISSUE TITLE
Citations not generated when inside *italic* or <em> tags

### ISSUE THREAD

**Issue by risangbaskoro** [timlrx/rehype-citation#49]
I am using [Quartz](https://quartz.jzhao.xyz/) to build my blog/notes. In this blog, I want to have both citations and image captions.

For image captions, I am using the [rehype-image-caption](https://github.com/Robot-Inventor/rehype-image-caption) package, which wraps the caption inside a `figcaption` within a `figure` tag, using the following markdown syntax:

```markdown
![alttext](some-image.jpg)
*Some caption that explains the image.*
```

This works as expected. However, I encountered an issue when trying to include a citation _inside_ an image caption. Here's the markdown I used:

```markdown
*An elephant drinking water from Nile river. [@doe2024]*
```

Instead of rendering the citation, it produces the following HTML output:

```html
<em>
	An elephant drinking water from Nile river. [@doe2024]
</em>
```

## Expected Behavior

The expected HTML output should look something like this, where the citation is properly parsed and generated inside the `<em>` tag:

```html
<em>
	An elephant drinking water from Nile river.
	<span class="" id="citation--myself2024--1">
		(
		<a href="#bib-myself2024">Doe, 2022</a>
		)
	</span>
</em>
```

or, inside a `figcaption`:

```html
<figcaption>
  An elephant drinking water from Nile river.
  <span class="" id="citation--myself2024--1">
  (
    <a href="#bib-myself2024">Doe, 2022</a>
  )
  </span>
</figcaption>
```

**Additional Information**:
- I am not familiar with Typescript or Javascript, so I'm unsure if this is related to how `rehype-citation` handles content within `<em>` or similar tags.
- I am using `rehype-citation` version `^2.1.1` along with the lastest version`rehype-image-caption`.

Could you provide guidance on how to address this issue? Is there a possible fix or workaround?

# EDIT:
After seeing #25, I am wondering if we can include em or figcaption in permittedTags? What would be the trade-off?

https://github.com/timlrx/rehype-citation/blob/fc0fde0764096958185cbd997c82f4cba76c963a/src/generator.js#L30

**Comment by halafy-ds** [comment]
Hi, as a workaround if your Markdown application/processor supports HTML, you can simply wrap the citation by a <span> tag. This way the parent tag will be in the permittedTags list.

**Comment by risangbaskoro** [comment]
Ah, well, you're right. That resolves the issue. 😅

I am closing this now.
