### ISSUE TITLE
bug: regression made from #44

### ISSUE THREAD

**Issue by aarnphm** [timlrx/rehype-citation#50]
With 2.1.2, doing the following works with relative path when importing bibliography file:

```js
[rehypeCitation, {
  bibliography: ["./content/References.bib", "https://...."], ...
}]
```

However,in 2.2.0, the path resolution somehow was concatenated twice with the same configuration:

```text
ENOENT: no such file or directory, open '/Users/repo/workspace/garden/Users/repo/workspace/garden/content/References.bib'
```

**Comment by timlrx** [comment]
Do you have a small reproducible example or repository that I can try out? Can't seem to replicate the issue on my end, thanks

**Comment by aarnphm** [comment]
I made a repo here https://github.com/aarnphm/citation-repo

**Comment by timlrx** [comment]
This is tricky to resolve since I can't reproduce it. Could some other plugins mistakenly modify the paths? Could you try using rehype-citation as the only rehype plugin? Also, does it work if you only provide one bib file?

**Comment by aarnphm** [comment]
modifying `cwd`? I don't think so otherwise, previous version would also fail right?

It works if there is only one bib file

**Comment by timlrx** [comment]
I meant the plugins over here: https://github.com/aarnphm/citation-repo/blob/1b80d71958dec02f8312934adf833a6643e43750/quartz.config.ts#L56-L100.

I don't see how the change from v2.1.2 to v2.2 would affect this so there's probably something else affecting the paths...

**Comment by aarnphm** [comment]
None of them modify path afaik. but a single bib path works so I'm not entirely sure how that works

**Comment by aarnphm** [comment]
None of them modify path afaik. but a single bib path works so I'm not entirely sure how that works
